### ISSUE TITLE
"counts" section of the /crawl endpoint has very inconsistent key names

### ISSUE THREAD

**Issue by MarkusTeufelberger** [XRPLF/rippled#2856]
Here's a current example of the data that is exposed:

```
"counts":
{
"AL_hit_rate":13.04347801208496,
"HashRouterEntry":3615,
"InboundLedger":82,
"Ledger":93,
"NodeObject":4009193,
"RCLCxPeerPos::Data":260,
"SLE_hit_rate":0.7297560975609756,
"STArray":3024,
"STLedgerEntry":918,
"STObject":32623,
"STTx":2986,
"STValidation":401,
"Transaction":330,
"dbKBLedger":2876,
"dbKBTotal":53629,
"dbKBTransaction":48894,
"fullbelow_size":1183851,
"historical_perminute":84,
"ledger_hit_rate":9.79262638092041,
"node_hit_rate":0.01132712606340647,
"node_read_bytes":1092703150,
"node_reads_hit":3954570,
"node_reads_total":3980180,
"node_writes":57087,
"node_written_bytes":30015185,
"treenode_cache_size":4009112,
"treenode_track_size":4009112,
"uptime":"20 minutes, 22 seconds",
"write_load":0
}
```

There is a mixture of snake_case, CamelCase, C++::Namespace::Names, Uppercase and lowercase in there.

The data that is exposed is also not really documented (https://developers.ripple.com/get_counts.html - "The list of fields contained in the result is subject to change without notice, but it may contain any of the following (among others) [...]"). The icing on the cake imho is the uptime that's reported as a custom string instead of as an integer of seconds. ;-)

Please decide on a format (you seem to use lowercase_snake_case everywhere else) and if possible also document what these numbers mean.

**Comment by nbougalis** [comment]
The names are "inconsistent" because they come from different sources. For example, `STTx` is the actual name of a class, and that name is used as the name of the counter associated with such classes. Honestly, I don't think that the particular choice of naming matters in this instance; this particular object is just a property bucket - a collection of name/value pairs.

I hear you about improved documentation: it is important and I'm going to open an issue to get that started. Also, fully agree that the `uptime` field should certainly be in seconds and not a human-readable string.

**Comment by intelliot** [comment]
Closing in favor of https://github.com/XRPLF/xrpl-dev-portal/issues/519
