### ISSUE TITLE
Remove long-deprecated account_tx switch

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/rippled#2926]
_(Porting this issue from Ripple's internal Jira ticket RIPD-1569)_

## Description

The account_tx method has an "old" mode that's been deprecated since at least 2013, with a ["temporary switch"](https://github.com/ripple/rippled/blob/develop/src/ripple/rpc/handlers/AccountTxSwitch.cpp) to use the old mode if people provide certain parameters (offset, count, descending, ledger_max, or ledger_min) in the request, and the new mode otherwise.

I'd say it's about time to remove the old mode.

## Blocker

Per @scottschurr:

> I made a run at this fix, but there's a complication. The command-line version of the account_tx command relies on the deprecated form of the RPC command. Until we come up with a new version of the command line (and figure out a transition process between the old and new forms) we're stuck with the deprecated version of the RPC command.
> 
> From a development perspective, the simplest possible change to the command line form would be to simply remove it and tell folks they must use the json command-line command to do account_tx queries. This approach requires no transition process and requires no new code.
> 
> I'm unsure just how user hostile that approach would be, however.
> 
> I welcome other suggestions.

**Comment by cjcobb23** [comment]
@mDuo13 @scottschurr For the command line, there are really only two fields that require calling the legacy handler: count and offset. I propose we simply ignore these fields if they are present, and include a warning in the response.

The other legacy fields can be easily mapped to a non-legacy field: descending is the same as forward. ledger_min and ledger_max are the same as ledger_index_min and ledger_index_max. Since the command line version parses arguments based on position, as opposed to the fields being named, we can just interpret these legacy values as their non-legacy analogues.

**Comment by scottschurr** [comment]
@cjcobb23, thanks for looking at this.  Your proposal seems reasonable to me.  Let's see what @mDuo13 thinks.

**Comment by mDuo13** [comment]
I'm all in favor of it.

**Comment by mDuo13** [comment]
The switch for the legacy code was removed as part of #3609. However, some of the old code is still lingering around, e.g. https://github.com/ripple/rippled/blob/master/src/ripple/rpc/handlers/AccountTxOld.cpp

**Comment by 1LISA2** [comment]
![images](https://user-images.githubusercontent.com/103248540/188114267-d835fc2b-60f2-47fd-8c13-bdfd47357e52.jpeg)
