### ISSUE TITLE
InsufficientNetworkMode, but server_info returns, that node is fine

### ISSUE THREAD

**Issue by skinderis** [XRPLF/rippled#2928]
I am getting an error while trying to call `account_info`, it returns an error:
```
{'error': 'noNetwork',
 'error_code': 17,
 'error_message': 'InsufficientNetworkMode',
 'request': {'account': 'rJ6QnMVvV4Y746vcEoMaQRztRQZ8YFaN64',
  'command': 'account_info',
  'ledger_index': 'current',
  'queue': True,
  'strict': True},
 'status': 'error'}

```

`server_info` method returns:

```
{'info': {'build_version': '1.2.4',
  'complete_ledgers': '47060752-47065389,47065491,47065593-47065595,47065675-47066170,47068643-47068660,47068744-47069038,47069119-47069204,47069305-47069308,47069411,47069515-47069518,47069637-47069640,47069759,47069874-47070099,47070164-47070572,47070681-47072088,47072202,47072306-47072315,47072456-47072472,47072752',
  'fetch_pack': 3581,
  'hostid': '8e27ef7c8d59',
  'io_latency_ms': 1,
  'jq_trans_overflow': '3718',
  'last_close': {'converge_time_s': 2, 'proposers': 0},
  'load': {'job_types': [{'avg_time': 8,
     'job_type': 'ledgerRequest',
     'peak_time': 26},
    {'job_type': 'untrustedProposal', 'peak_time': 2, 'per_second': 30},
    {'in_progress': 2, 'job_type': 'ledgerData', 'waiting': 26},
    {'in_progress': 1, 'job_type': 'clientCommand'},
    {'in_progress': 2, 'job_type': 'updatePaths'},
    {'job_type': 'advanceLedger', 'peak_time': 14, 'per_second': 19},
    {'job_type': 'trustedValidation', 'peak_time': 14, 'per_second': 9},
    {'job_type': 'writeObjects', 'peak_time': 14, 'per_second': 8},
    {'job_type': 'trustedProposal', 'peak_time': 2, 'per_second': 6},
    {'job_type': 'heartbeat', 'peak_time': 1},
    {'job_type': 'peerCommand', 'per_second': 486},
    {'job_type': 'diskAccess', 'peak_time': 14, 'per_second': 8},
    {'avg_time': 2,
     'job_type': 'SyncReadNode',
     'peak_time': 271,
     'per_second': 192},
    {'avg_time': 2,
     'job_type': 'AsyncReadNode',
     'peak_time': 303,
     'per_second': 400}],
   'threads': 6},
  'load_factor': 1,
  'peer_disconnects': '6',
  'peer_disconnects_resources': '0',
  'peers': 10,
  'pubkey_node': 'n9Kp8JVVwXpG9SQFiaWKyFNycVfT5Kmv8SvQgZ7dAAVdFFJBicCH',
  'pubkey_validator': 'none',
  'published_ledger': 47072752,
  'server_state': 'full',
  'server_state_duration_us': '7047263271',
  'state_accounting': {'connected': {'duration_us': '18619112330',
    'transitions': 18},
   'disconnected': {'duration_us': '2860929', 'transitions': 1},
   'full': {'duration_us': '43396816525', 'transitions': 76},
   'syncing': {'duration_us': '2045643528', 'transitions': 93},
   'tracking': {'duration_us': '27', 'transitions': 76}},
  'time': '2019-May-07 08:44:29.226449',
  'uptime': 64064,
  'validated_ledger': {'age': 4208,
   'base_fee_xrp': 1e-05,
   'hash': 'F2DEC6A60A6A0F33A37382135A71E10E16F36F4899884F1D0411F57FCE2588E9',
   'reserve_base_xrp': 20,
   'reserve_inc_xrp': 5,
   'seq': 47072777},
  'validation_quorum': 24,
  'validator_list': {'count': 1,
   'expiration': '2019-Jun-03 00:00:00.000000000',
   'status': 'active'}},
 'status': 'success'}
```

So it seems that node is working fine, it's server_state is full, peers are fine, complete_ledgers are also seem to be fine. But why then I am getting this error?

Thanks!

**Comment by miguelportilla** [comment]
The validated ledger described in your `server_info` result is `4208` seconds old, which is quite old. The `account_info` RPC command will return `InsufficientNetworkMode` if the ledger's age specified by the `ledger_index` field (The `current` ledger in this case) is older than 120 seconds. Your `server_info` is showing too many transitions between the `tracking`, `syncing` and `full` modes for such a short `uptime` period. It appears your server is having difficulty maintaining synchronization with the network.

**Comment by skinderis** [comment]
Yea. The problem was that before I was running a node that wasn't trusting other validators. Then I configured it to trust other validators and didn't delete old files.

**Comment by skinderis** [comment]
I have the same issue still, sometimes it gets stuck for some reason and sometimes it works smoothly. 
What would be your suggestions? Server is quite strong.

**Comment by miguelportilla** [comment]
Servers with sync difficulty usually suffer from insufficient disk IOPS and or invalid config file settings. The validators section is especially important. As a minimum, a server should have a 4 core modern x86 CPU, 16GB memory and an SSD drive. It is important that disk performance doesn't drop below 10k IOPS. Often, hosting solutions mention peak performance, not sustained minimums. Other processes or periodic jobs running on the same server can also cause desynchronization. For instance, a periodic job running a disk intensive process such as a backup. It is a best practice to minimize other software from operating on the same machine.

**Comment by mDuo13** [comment]
Another that can affect sync with the network is maintaining steady connectivity with peers in the network. If you are behind a firewall and you don't open the peer protocol port (51235 by default), then you can only rely on outbound peers, who tend to be busier and may drop you as a peer. It's also possible you may end up connected to test net peers only when you want to be on the main net, or vice versa (look for "`insane` in the `peers` response)

So two actions you can take to reduce connectivity-related problems are:

- Make sure you configure port forwarding in your firewall. (It can help to restart your server afterward, since that'll prompt it to look for new peers including ones who can now connect to you.) After you do this, you should see some `"type": "in"` peers in the [Peer Crawler](https://xrpl.org/peer-crawler.html) response.
- Actively manage your peers, for example with a script such as [rbh](https://github.com/gnanderson/rbh)

**Comment by carlhua** [comment]
We should look at the value of `server_state` when it is generated.

**Comment by mDuo13** [comment]
Yeah, I suspect `server_state` should _not_ be `full` if the validated ledger is more than 20 seconds old, with the possible exception of stand-alone mode.

**Comment by scottschurr** [comment]
Currently the reported `server_state` is at best `connected` if the validated ledger is more than 1 minute old.  Is the suggestion that the mode should be, at best, `tracking` if the validated ledger is more than 20 seconds old?  That would be an easy check to add.

I'm a little worried about picking 20 seconds as a threshold.  If on a network with no traffic ledgers close every 20 seconds.  In that case a server that is fully synced would be reporting `tracking` simply because there was not enough network traffic.  I think 30 seconds might be a safer threshold than 20.  But I'm open for discussion.

**Comment by mDuo13** [comment]
> Currently the reported server_state is at best connected if the validated ledger is more than 1 minute old.

The `server_info` from the thread opener shows a validated ledger 4208 seconds old but server_state value of "full" so there is some sort of bug or edge case in which that is not true.

**Comment by intelliot** [comment]
@skinderis we haven't seen this issue on servers with sufficient specs and good connectivity. There have also been significant improvements to syncing over the past year. If problems persist, please open a new issue (and feel free to link back to this one if there's context here that's still relevant).
