### ISSUE TITLE
README should contain link to in-repo build-doc

### ISSUE THREAD

**Issue by ghost** [XRPLF/rippled#2987]
## Current Status

A link to an external document at the end of the README points to install/build-instructions on a developer-resource:

https://developers.ripple.com/install-rippled.html

## Expected

README points to an repo-internal file (e.g. `INSTALL.md` or `BUILD.md`), thus the code can be build (tested, installed, simple-setup-executed) without relying on external information.

## Rationale

The build-instructions are an integral part of a code-repository.

**Comment by MarkusTeufelberger** [comment]
This is already the case.

https://github.com/ripple/rippled/blob/develop/README.md#see-also

**Comment by MarkusTeufelberger** [comment]
Oh, I misunderstood. I thought you wanted a link to a build guide.

In my opinion it is not necessary to dumpicate the content in this repository, it is simple enough to look at the CI files or just build using CMake anyways.

**Comment by lazaridiscom** [comment]
No, it's not. Please reread.

**Comment by lazaridiscom** [comment]
> to duplicate the content in this repository

Anything "source-code build" related should be moved to the repo (away from the external docs)

>  it is simple enough to look at the CI files or just build using CMake anyways.

No, it's not "simple enough". Simple enough is following / copy&paste of instructions given by gentle & capable doc-writers, see e.g.:

https://github.com/facebook/folly#build-notes

(but this project feels anyaways dead, there is zero maintainers traffic...)

**Comment by sublimator** [comment]
I don’t think “dead” so much as settled :) The maintainers work slowly and
cautiously. Not a bad thing when money is concerned.

The basic ledger design is pretty much set in stone at this point so it’s
just leisurely debates on the finer points of things and keeping up to date
with dependencies etc.

Work continues behind the scenes on consensus research however.

It’s the base layer for the xSuite of products, which aren’t open source
sadly. I am guessing that is where most of the ripple development happens.

**Comment by thejohnfreeman** [comment]
I agree that build instructions should be in the README, even if they are simple. The CI scripts are complicated and sparsely commented; I chose to rewrite them so that I could understand them, to separate build from test, and so that they could be invoked by humans outside of a CI environment. I don't think new users / contributors should be expected to dig into them.

That said, this would make an excellent first contribution. Would you like to do it, @lazaridiscom?

**Comment by thejohnfreeman** [comment]
Note that build instructions are included in READMEs under the `Builds` directory. The top level README just needs to link to them.

**Comment by lazaridiscom** [comment]
>> (but this project feels anyaways dead, there is zero maintainers traffic...)

@sublimator , thanks for your elaborations. The "settled" status explanations sound like something the README could tell a visitor, possibly even together with the info about consensus-work and non-public projects (so one knows what to expect here).

Additionally, issues should be pre-processed/labeled (see #2989)

Personally i visited ripple in context of a cross-comparison (several high-profile C++ based crypto-projects), in order to select a code-base which is worth a full teach-in.

> Would you like to do it, @lazaridiscom?

@thejohnfreeman , I can take a look. It seems like everything is in the repo anyways (as you mentioned, e.g. https://github.com/ripple/rippled/tree/develop/Builds/linux)
