### ISSUE TITLE
CONTRIBUTING.md is missing

### ISSUE THREAD

**Issue by denizdanaie** [XRPLF/rippled#3312]
## Summary

After a thorough search for a document that would guide a new contributor where to start in `rippled` repository,  I concluded that there is none for this project, and I decided to suggest it as an issue.

There is already a `CONTRIBUTING.md` file for `xrpl-dev-portal` repository, though that is aimed for that specific repository.

## Motivation

I am taking a course, which I am studying ripple in detail. One of my tasks for this course is to contribute to this project. 
I first started by checking the label `good first issue`. However, I was lost after 10 min since I did not know where to start, what I need to know beforehand, which parts of the code I should first study to understand the basics of the underlying system, how to set up the environment for developing and contributing to the project, and so on.

## Solution

Simple! :blush: Adding contribution.md just like other open-source projects! i.e., [ATOM](https://github.com/atom/atom/blob/master/CONTRIBUTING.md)'s contributing.md

**Comment by thejohnfreeman** [comment]
Great questions. I'll try to give a few answers. Maybe as others chip in, we can collate the answers into a `CONTRIBUTING.md` at the end.

For build, there are instructions buried in the repository for [Linux](https://github.com/ripple/rippled/tree/develop/Builds/linux), [Mac](https://github.com/ripple/rippled/tree/develop/Builds/macos), and [Windows](https://github.com/ripple/rippled/tree/develop/Builds/VisualStudio2017). They should be mostly up-to-date, but they are only ever tested by new contributors like yourself. If you run into trouble, please open more issues.

For an overview of the codebase, there's a good [audit](http://wipple.devnull.network/research/rippled.html) from another contributor, @movitto, of the code for version 1.1.0. Because it is actively developed, rippled is a moving target, so any audit of a specific version will fall out-of-date as it ages, but the core of rippled is pretty stable, so the audit is still mostly applicable for now. I'd like to see us contribute more such documentation into the codebase, near the code, and render it with Doxygen online. I'm hosting the latest version, for 1.5.0, from [my fork's `gh-pages` branch](https://thejohnfreeman.github.io/rippled/). Poke around the [Related Pages](https://thejohnfreeman.github.io/rippled/pages.html) for some overviews (rendered from Markdown documents sprinkled through the codebase).

**Comment by carlhua** [comment]
to add on what @thejohnfreeman has provided, consider this feature request itself a potential "contribution" to the project @denizdanaie ! We would love to have external contributors to help us make the project better. As you find your ways around the project, feel free to ask questions as we are here to help. In addition, consider making a contribution (PR) to this feature request as you see fit!

**Comment by sneh19337** [comment]
I would take the help of all the resources mentioned above and will send a PR of Contributing.md

**Comment by wojake** [comment]
Ye, we really need a `CONTRIBUTING.md`, I was pretty confused when browsing the repo because the CONTRIBUTING.md was no where to be found.

**Comment by intelliot** [comment]
Completed by https://github.com/XRPLF/rippled/pull/4214
