### ISSUE TITLE
account_objects CLI usage statement is wrong (Version: 1.5.0)

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/rippled#3329]
## Issue Description
(Discovered while documenting #3196.) The usage statement for the `account_objects` method is wrong. [[Source code]](https://github.com/ripple/rippled/blob/f00f263852c472938bf8e993e26c7f96f435935c/src/ripple/app/main/Main.cpp#L135)

The account_objects method does not support the `strict` parameter, but the commandline implies it does.

## Steps to Reproduce

Start rippled in stand-alone mode, then run this command:

```sh
rippled account_objects masterpassphrase current strict
```

## Expected Result
The result should be an `actMalformed` error, similar to what you get if you do `account_info` with the same arguments.

```json
{
   "result" : {
      "error" : "actMalformed",
      "error_code" : 35,
      "error_message" : "Account malformed.",
      "request" : {
         "account" : "masterpassphrase",
         "api_version" : 1,
         "command" : "account_objects",
         "strict" : 1
      },
      "status" : "error"
   }
}
```

The "easy" fix is to correct the usage statement not to mention the `strict` parameter, which is not supported in any interface for `account_objects`. But my preferred fix is to **add `strict` support to `account_objects`** for consistency with other account_* methods.

## Actual Result
The server returns a successful response for the genesis account:

```json
{
   "result" : {
      "account" : "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh",
      "account_objects" : [],
      "ledger_current_index" : 3,
      "status" : "success",
      "validated" : false
   }
}
```

**Comment by intelliot** [comment]
Considering https://github.com/ripple/rippled/issues/3330, for account_objects specifically, I think a reasonable path forward would be to change it so that `strict` behavior is the default (i.e. the account field should only accept a public key or XRP Ledger address). Allowing a secret or passphrase is a bug (@nbougalis agrees) and I doubt there are many (if any) apps relying on this behavior, so it's OK to fix this without bumping the api_version. (Of course, if someone prefers to bump the api_version, that's fine too.)

**Comment by drlongle** [comment]
I created [PR 4404](https://github.com/XRPLF/rippled/pull/4404) to address #4337. Coincidentally, I also address this issue.
