### ISSUE TITLE
Simplify and constexpr-ize SField

### ISSUE THREAD

**Issue by carlhua** [XRPLF/rippled#3441]
## Summary
As of C++14, constexpr support in the language has gotten to the point that we ought to be able to build all of the SFields, and their supporting lookup tables, at compile time. Here are the steps to get there:

1. The system currently supports dynamic creation of SFields. I think that's wrong, but I need to confirm that with the team. If the team agrees that dynamically creating SFields is wrong, then I need to rip out that capability and fix the unit tests.

2. Get rid of SField::fieldName, SField::getName(), and SField::getJsonName(). Aim all uses of those members to use the jsonName member. I've already made a full pass through the code to do this, so I know it can be done. In the process, change the jsonName member to simply be called "name".

    All of this work is worthwhile on its own. If we stop here we will still have achieved a minor victory.

3. All SField fields are now constexpr friendly. Making the SField constructor constexpr friendly should now be trivial. The hard part is building the lookup table at compile time. I think this will either involve listing each SField twice or using preprocessor trickery to build the lookup table. I'll need to take a poll of the team to see which they prefer. Once a direction is chosen, make all SFields constexpr and build the lookup table at compile time.

4. Rename JsonFields.h to JSS.h or jss.h (poll the team). Put that in it's own commit so git can track the rename more easily.

5. Remove all of the SFields that are currently present in jss.h. Have their uses refer to the appropriate SField.name member.

Exported from RIPD-1717

**Comment by scottschurr** [comment]
Some of this work has already been done:

- Dynamic creation of `SField`s has already been removed.
- The rename of JsonFields.h to jss.h has already occurred.
- At least at one point all of the `SField` names had been removed from jss.h.

But that leaves the most interesting part of the work:

- Making the `SField` constructor `constexpr` and
- Building the list of `SField`s at compile time.

The question remains, how does the codebase benefit from the change?  The benefits are all small.

- Building the `SField`s and their map at compile time removes the cost of construction from startup-time.  All `SField`s and their map would be built at compile time.  This provides a tiny improvement in startup time.
- Since the `SField`s are built at compile time, all access to`SField`s by name, as well as access to their fields, can also be done at compile time.  This would squeeze a tiny bit more speed out of executing code that uses the `SField`s.
- Because `SField`s and their fields are available at compile time, certain `assert`s could be potentially be changed to `static_assert`, which would cause compile-time failures rather than runtime failures.  But there would not be a lot of that kind of error checking.

While those changes would provide speedups, they would probably be invisible compared to things like database access and uses of the freestore.

So, while this would be a useful change to make, I cannot argue that it has high value for the codebase.
