### ISSUE TITLE
Improve shard distribution/selection algorithm

### ISSUE THREAD

**Issue by carlhua** [XRPLF/rippled#3501]
The current algorithm chooses a shard index at random and while this works well, it may produce a U-shaped curve for ledger availability. The following logic will improve distribution. Every server that has shards must make a sane decision whether or not to store the new shard. If M is the number of shards we can hold and N is the number of shards in existence, we replace a random shard with the current shard with probability M/N.

Let's use this issue to track the shard selection algorithm @miguelportilla 

Exported from RIPD-1584

**Comment by intelliot** [comment]
History sharding is effectively deprecated in favor of [Clio](https://github.com/XRPLF/clio)

**Comment by MarkusTeufelberger** [comment]
Isn't that a completely different use case?

**Comment by intelliot** [comment]
@MarkusTeufelberger - what do you mean?

[History sharding](https://xrpl.org/history-sharding.html) was a way to store old ledger history. [Clio](https://xrpl.org/the-clio-server.html) stores old ledger history.

**Comment by MarkusTeufelberger** [comment]
History sharding stores raw old ledger data, Clio offers limited views on that data via APIs.

**Comment by intelliot** [comment]
Clio is intended to provide all old ledger data. Is there anything that's missing? What's the use case for "raw"?

**Comment by MarkusTeufelberger** [comment]
Inner nodes for example are missing as far as I know. Without them you can not validate root hashes. Yes, you can calculate them from full ledgers, but I don't see Clio doing this (maybe I'm mistaken). Also Clio is a downstream project that seems to have its own issues and release cycle.

The use case for "raw" is to have a definite, trustlessly distributable and canonical state storage for all ledger data that hasn't been lost so far, meaning "full history servers". Bugs like [this](https://github.com/XRPLF/clio/issues/92) would mean actual data loss if only Clio is used to store old ledger history. The fact that this data integrity issue stays open unfixed for 1.5 years and running does not make me trust this solution by the way. Clio also by design violates the trustless principle for example:

> It uses gRPC to get validated data from one or more **trusted** rippled servers that are connected to the P2P network.

This is fine by the way, Clio is helpful in taking load off of servers that should be busy making forward progress, not serving up random pieces of history. I disagree that it is the place to actualy store this data though (should people in the future be really expected to run a full Cassandra/ScyllaDB cluster just to have ledger data available for their needs?).

If you don't have a full history node, you can't really use Clio without trust. If you want to set up a full history node, (deterministic) shards are the operationally _much_ easier and faster way to get there than waiting for months for p2p sync or again trusting someone with a nodestore dump.

**Comment by intelliot** [comment]
> should people in the future be really expected to run a full Cassandra/ScyllaDB cluster just to have ledger data available for their needs?

Why not? Cassandra or ScyllaDB can be run locally.

We can discuss with the Clio team about having a way for Clio to store inner nodes and/or full ledgers.

**Comment by sublimator** [comment]
I still like the idea of history packs for history purposes.

### Components of a Ripple History Pack

1. **Ledger Header**: Essential metadata like ledger index and root hashes.
2. **Transaction Trees**: Full transaction sets per ledger.
3. **AccountState Trees**: Initial full tree, followed by deltas for subsequent ledgers.

### Ripple History Pack Structure

A Ripple history pack file (e.g., `xrpl-history-1-500-000-to-1-600-000.bin.gz`) would include:

- Ledger 1,500,000: Header, Full AccountState Tree, Full Transaction Tree
- Ledger 1,500,001: Header, AccountState Delta, Full Transaction Tree
- ...
- Ledger 1,600,000: Header, AccountState Delta, Full Transaction Tree

### Implementation Details

1. **Format**: XRPL's native canonical binary.
2. **Compression**: gzip or similar.
3. **Inner Nodes**: Implied, only leaves stored for deltas.

### Advantages

1. **Efficiency**: Reduced redundancy with deltas.
2. **Verifiability**: Cryptographic integrity checks.
3. **Scalability**: Lower storage needs.

### Use Cases

1. **Auditing**: Immutable records for scrutiny and verification.
2. **Archive Service**: Downloadable history packs for quick node bootstrapping or data analysis 
3. **Database [Re]seeding**: Could make very fast custom importers for things like Clio
