### ISSUE TITLE
Consider automatically generate enum definitions during compilation

### ISSUE THREAD

**Issue by carlhua** [XRPLF/rippled#3657]
The binary enum definitions should be generated from the rippled code automatically whenever there is a new rippled release.

We should consider how this (interpreted broadly) can be handled so that other packages that rely on the binary representation can be automatically updated.

Options include having a descriptor file in some DSL and a script that parses it to generate the necessary definitions. The script could be packaged and be used as part of the build, and we could have some kind of “hook” on GitHub that runs, generates the files, and updates repos we have push access to (e.g. the JS binary codec).

Exported from RIPD-1305

**Comment by intelliot** [comment]
From RIPD-1305 on Jira:

That is how it was originally generated, but it's not working well to manually update it every time, especially after a rippled release (when the definitions can change).

Consider having enums/definitions consolidated into one place (whether from the same repo or in an independent repo) so that other software with dependency on these definitions can automatically parse.

**Comment by intelliot** [comment]
I believe this will be resolved by https://github.com/XRPLF/rippled/pull/4402 and related work

**Comment by intelliot** [comment]
Fixed by https://github.com/XRPLF/rippled/pull/4703.
