### ISSUE TITLE
Why does the ledger_index start at 0 every time I restart the node?

### ISSUE THREAD

**Issue by COLUD4** [XRPLF/rippled#4335]
Why does the ledger_index start at 0 every time I restart the node?
![截屏2022-11-04 15 16 34](https://user-images.githubusercontent.com/21240219/199914927-9fe87318-6d6c-431a-a534-484c120aeb5d.png)

**Comment by intelliot** [comment]
Are you trying to sync with a known network (such as [Mainnet or Testnet](https://xrpl.org/parallel-networks.html)), or are you running in [stand-alone mode](https://xrpl.org/use-stand-alone-mode.html)?

Either way, when a server is first started, it will automatically run consensus on its own and close ledgers over time. However, these ledgers won't necessarily be validated - that depends on the [validators](https://xrpl.org/validators.html) you've chosen (and configured). Until your server syncs with the network, your server will maintain a local ledger that has no relation to the one that the trusted validators are validating. If your server meets the [requirements](https://xrpl.org/system-requirements.html), your node should usually sync in less than 30 minutes.

**Comment by nbougalis** [comment]
When the server restarts, it does not know the state of the network that it's supposed to connect to. It internally creates a new genesis ledger (which is, of course, not validated and it's just meant as an internal scratchpad) and continues updating that while it's trying to catch up to the network. Once it does, the ledger chain it internally created is discarded and it switches to the validated ledger, according to its UNL.

As to why... well, that's because how it was coded. It could have been coded differently (and it could be changed now) to re-load the ledger ledger it observed as validated and attempt to continue from there (indeed, that is what [`fast_load`](7c12f0135897361398917ad2c8cda888249d42ae) tries to do and what other changes, like forward replay, _will_ do).

Generally, the existence of this ledger chain during startup should be thought of as an internal implementation detail.

**Comment by intelliot** [comment]
No changes specific to this issue are required in rippled, so we're closing this issue. But we did open an issue for xrpl.org for documenting this behavior. https://github.com/XRPLF/xrpl-dev-portal/issues/1681
