### ISSUE TITLE
When there are no offers, nft_sell_offers should return an empty list (Version: 1.9.4)

### ISSUE THREAD

**Issue by intelliot** [XRPLF/rippled#4339]
## Issue Description

`nft_sell_offers` returns `objectNotFound` for a valid NFT when there are no offers.

## Steps to Reproduce

Example:

https://xrpl.org/websocket-api-tool.html?server=wss%3A%2F%2Fs2.ripple.com%2F&req=%7B%22command%22%3A%22nft_sell_offers%22%2C%22nft_id%22%3A%2200090000D0B007439B080E9B05BF62403911301A7B1F0CFAA048C0A200000007%22%2C%22ledger_index%22%3A%22validated%22%7D

With nft_info, we can see that the NFT exists.

## Expected Result

An empty list (or empty array), and no error message.

## Actual Result

An error message - `objectNotFound`.

Currently, this means "the object wasn't found", where the "object" is the list of buy or sell offers.

## Environment

Mainnet (s2.ripple.com)

Note: This would need to be updated in both `rippled` and `Clio`.

**Comment by ledhed2222** [comment]
the issue here is that there is no way to distinguish between the following two cases:

1. user asks for offers for an NFT that exists, but which has no offers
2. user asks for offers of an NFT that does not exist (either because it was never made or because it was burned)

obviously the ideal user experience is that 1. returns an empty array but 2. returns `object_not_found`. However, that is not feasible on `rippled` because of the way that all o fthis is stored.

So, if we made this API return an empty list, it would also return an empty list for scenario 2. In my opinion, that's not that much better than what we had before, and has the added pain of requiring all users of this API to swap how they handle these cases.

**Comment by ximinez** [comment]
There are a lot of parallels between NFT offers, and DEX offers. If I ask rippled for the `book_offers` for a pair that doesn't exist, I get an empty array if the issuer exists.
```
$ rippled -q book_offers XRP ABC/rhub8VRN55s94qWKDv6jmDy1pUykJzF3wq
{
   "result" : {
      "ledger_current_index" : 78129811,
      "offers" : [],
      "status" : "success",
      "validated" : false
   }
}
```
If the issuer doesn't exist, I get a specific error: `"Invalid field 'taker_gets.issuer', bad issuer."`.

**Comment by ledhed2222** [comment]
@ximinez - right but when a token is burned the DirectoryNodes that link that token ID to its offers are also removed. And without knowing the owner of the token at the specified ledger height (which is not part of the API) we cannot determine if the token exists. This is really the same issue as what motivated `nft_info` in clio - without knowing the NFT's owner you cannot get the NFT unless you traverse the entire ledger.

**Comment by ximinez** [comment]
@ledhed2222 Makes sense.

**Comment by ledhed2222** [comment]
No i don't think it should be moved to clio. i think it should be documented and closed

**Comment by intelliot** [comment]
Opened issue for docs: https://github.com/XRPLF/xrpl-dev-portal/issues/1851
