### ISSUE TITLE
[transaction not found] (Version: [1.10.0])

### ISSUE THREAD

**Issue by xiongjiabing** [XRPLF/rippled#4487]
I noticed that a batch of transactions had been successfully broadcast to the node and returned tx_id, but when we tried to get the transaction information, we couldn't find it on the blockchain.  the following is the broadcast result of a transaction. could you take a look at it?

```json
{
  "result": {
    "broadcast": true,
    "account_sequence_available": 69954835,
    "applied": true,
    "open_ledger_cost": "10",
    "tx_json": {
      "Account": "rDAE53VfMvftPB4ogpWGWvzkQxfht6JPxr",
      "Destination": "rDxfhNRgCDNDckm45zT5ayhKDC4Ljm7UoP",
      "TransactionType": "Payment",
      "TxnSignature": "3044022003F25A89BFD5A36A46B47269DAFCFC1F7246B0B08C52665A41F359960CE8330B02204FF87F8A4EC05CA1348B2697DAD25B5ED47F94DBDCEAB3ABEC11DD6BDA98698F",
      "SigningPubKey": "036085B9E6A6C3628E94FB87914AD5CBABB1DD5FA510D50D742919DC5684A43900",
      "Amount": "7957206868",
      "Fee": "3000",
      "Flags": 2147483648,
      "Sequence": 69954834,
      "DestinationTag": 1000010862,
      "LastLedgerSequence": 78876808,
      "hash": "2801C3CD8EA8DD9E5605F86382E8DE363EB0166E5DACB323A38FDB7C0CF9794A"
    },
    "queued": false,
    "engine_result_code": 0,
    "accepted": true,
    "kept": true,
    "validated_ledger_index": 78876793,
    "tx_blob": "120000228000000024042B6D122E3B9AF46E201B04B390886140000001DA495754684000000000000BB87321036085B9E6A6C3628E94FB87914AD5CBABB1DD5FA510D50D742919DC5684A4390074463044022003F25A89BFD5A36A46B47269DAFCFC1F7246B0B08C52665A41F359960CE8330B02204FF87F8A4EC05CA1348B2697DAD25B5ED47F94DBDCEAB3ABEC11DD6BDA98698F81148DE43FF9545F17CCD1174120F7E61CE47E77B01083148E0D713E837D8C34420B42F2CE1698BDFFB27FA5",
    "engine_result": "tesSUCCESS",
    "account_sequence_next": 69954835,
    "engine_result_message": "The transaction was applied. Only final in a validated ledger.",
    "status": "success"
  }
}
```

**Comment by xiongjiabing** [comment]
Now 39 transactions in a row have the same problem，It seems to be continuing to grow

**Comment by thejohnfreeman** [comment]
What method gave you this response? `submit`? This looks like a response indicating the transaction was successfully applied in the open ledger (meaning there would be no reason to exclude it from the next proposal), and broadcast to peers (so they can include it in their proposals), but like the `engine_result_message` says, the transaction is final only in a validated ledger. It did not appear in a validated ledger, so its effect was not final. The current ledger sequence has since past the `LastLedgerSequence`, so the transaction will need to be retried.

It's odd that it didn't make it into a ledger in the 15 ledger (~1 minute) window it had after it was submitted, but it's not impossible. It appears that the transaction for this account with the previous sequence number, [69954833](https://livenet.xrpl.org/transactions/DC9087CC3FB1EF22E73485071786AB19591FA47484B4290C556880B6EB1DB0D7/detailed), was applied in ledger [78876803](https://livenet.xrpl.org/ledgers/78876803), just 5 ledgers before the `LastLedgerSequence` of this transaction. A transaction with this sequence number, but not this transaction, was [applied](https://livenet.xrpl.org/transactions/1924393F7022FDCA5CD3E010AEDBE79F6A17CC62A3BA778712AECFB49025AA86/detailed) in ledger [78876824](https://livenet.xrpl.org/ledgers/78876824). You may need to review the lifecycle around [reliable transaction submission](https://xrpl.org/reliable-transaction-submission.html).

**Comment by xiongjiabing** [comment]
yes, it's is submit.  so, this transaction is not in a valid ledger，Is it still likely to succeed？ or I could say it has failed

**Comment by xiongjiabing** [comment]
yes, it's submit.  got it, thanks a lot

**Comment by xiongjiabing** [comment]
So the same sequence can only be used for one valid transaction, right？

**Comment by intelliot** [comment]
Yes, for any given account, only one transaction can ever be validated (finalized) with the same sequence number. The sequence number is comparable to the "nonce" used by some other blockchain systems.

**Comment by xiongjiabing** [comment]
I have another question, it used to be that there were fewer cases like this on our side. Looking at the time of the transaction, from 2023-04-04(UTC) the number of cases has increased, and I am a little puzzled as to why it has been rare before. Like the new batch today
