### ISSUE TITLE
[The same sequence of cases continues to increase] (Version: [1.10.0])

### ISSUE THREAD

**Issue by xiongjiabing** [XRPLF/rippled#4490]
https://github.com/XRPLF/rippled/issues/4487 continue this discussion.

I have another question, it used to be that there were fewer cases like this on our side. Looking at the time of the transaction, from 2023-04-04(UTC) the number of cases has increased, and I am a little puzzled as to why it has been rare before. Like the new batch today

**Comment by xiongjiabing** [comment]
We call "account_info" before each broadcast transaction and get its response "account_data.Sequence", which if retrieved correctly will be the sequence number of the submitting transaction

**Comment by xiongjiabing** [comment]
I mean is that instead of calling "account_info" to get the sequence, and i can maintain it myself, as long as it's unique

**Comment by xiongjiabing** [comment]
What I mean is that instead of calling "account_info" to get the sequence, I can maintain it myself as long as it is unique and increment

**Comment by intelliot** [comment]
Yes, you can maintain the Sequence number yourself. Each transaction must have a unique Sequence number, and it must be exactly 1 greater than the Sequence number of the previous tx sent from the given account. It is comparable to the "nonce" used by some other blockchains.

Since a blockchain (including the XRP Ledger) is a decentralized system, account_info is not always up-to-date. It depends on network propagation delays, tx processing time, consensus by validators, and how quickly you are submitting transactions. It is often best to track the Sequence number yourself. 

Note that if a transaction fails to be validated at all, the account's Sequence number will not increment. So if there is any possibility of your transaction being invalid or dropped (e.g. fee too low), then there is a possibility of a gap in Sequence numbers. You'll need to submit some transaction to fill the gap in order for transactions with higher Sequence numbers to become valid. The same situation occurs with the nonce on some other blockchains.

**Comment by xiongjiabing** [comment]
thanks a lot

**Comment by xiongjiabing** [comment]
In the "submit" RPC, I see that there are two parameters that we can maintain by ourselves (last_ledger_sequence & sequence) ，Is there any previous relationship between these two parameters？ for the last_ledger_sequence, I get it from server_state

**Comment by xiongjiabing** [comment]
hi, whether the LastLedgerSequence can be repeated for each transaction submit?

**Comment by scottschurr** [comment]
> hi, whether the LastLedgerSequence can be repeated for each transaction submit?

@xiongjiabing, briefly, yes, the `LastLedgerSequence` can be repeated in separate transactions from the same account.

To understand how to use these fields it helps to understand what they accomplish in the transaction.  Here is some introductory information.

- `Sequence`: https://xrpl.org/basic-data-types.html#account-sequence
- `LastLedgerSequence`: https://xrpl.org/reliable-transaction-submission.html#lastledgersequence

**Comment by xiongjiabing** [comment]
I see. thank you. If I want to maintain the sequence of accounts locally, do you have any specific implementation plan that you can recommend to me? Implementation process or pseudocode

**Comment by scottschurr** [comment]
You'll find documentation of reliable transaction submission here: https://xrpl.org/reliable-transaction-submission.html#reliable-transaction-submission  The documentation provides guidance for submitting transactions as well as discussing techniques for error handling.
