### ISSUE TITLE
[One address per master public key?] (Version: [1.11.0])

### ISSUE THREAD

**Issue by junghyun0783** [XRPLF/rippled#4687]
hello
I have a question.
You create an account using the master public key and create an address with that account.
But what I'm curious about is that an account can only create one address?
Or is it possible to create multiple addresses per account?

In other words, is it possible to create only one address with the master public key?

**Comment by intelliot** [comment]
It sounds like you are asking about hierarchical deterministic (HD) wallets. From a technical perspective, yes, you can generate any number of addresses (i.e. additional key pairs) from a single master key pair. However, this is considered bad practice on the XRPL because it is considered to be ledger spam. Any funds governed by a single key pair should generally be stored in a single on-ledger account in order to maximize efficiency. Additional accounts are best used when they have independent key management practices (potentially including the use of a regular key and/or [a signer list](https://xrpl.org/multi-signing.html)) so that there is a security reason for the on-ledger separation of funds. To encourage efficient use of ledger space, [reserve requirements](https://xrpl.org/reserves.html) impose some cost on all funded accounts.

**Comment by junghyun0783** [comment]
@intelliot 
Thank you for your kind reply.
Thanks to this, we were able to proceed quickly with development.
Thank you again.
