### ISSUE TITLE
OpenLedger::accept applies txns from current_ in order of hash/ID, which may lead to out-of-sequence apply. (Version: develop & 1.11.0)

### ISSUE THREAD

**Issue by ubuddemeier** [XRPLF/rippled#4953]
I'm working on a project that is based on the 1.11.0 rippled source. The issue described here is still present in the develop branch.

I noticed that OpenLedger::accept applies txns from the current open ledger in order of hash/ID, which is the ordering in the ledger.
If there are several txns from the same account in the current open ledger, this may lead to some or all of them to fail in preclaim, because they may be out-of-sequence if ordered in that way. If I sort the txns by SeqProxy before applying, they are successfully applied. See snipped below.

https://github.com/XRPLF/rippled/blob/develop/src/ripple/app/ledger/impl/OpenLedger.cpp#L102
https://github.com/XRPLF/rippled/blob/develop/src/ripple/app/ledger/OpenLedger.h#L218

    if (!current_->txs.empty())
    {
        std::vector<std::shared_ptr<STTx const>> txs;
        for (auto& tx : current_->txs)
            if (tx.first && !ledger->exists(tx.first->getTransactionID()))
                txs.push_back(tx.first);
        sort(txs.begin(), txs.end(), [](auto const& tx1, auto const& tx2){ return tx1->getSeqProxy() < tx2->getSeqProxy(); });
        apply(
            app,
            *next,
            *ledger,
            txs,
            retries,
            flags,
            j_);
    }

Am I missing something here?

**Comment by ximinez** [comment]
Interesting observation. The thing I think you're missing is that the ordering is to reduce the change of any particular account or transaction having an unfair advantage over any other. However, I don't think this design accounted for the possibility that an account would have more than `LEDGER_TOTAL_PASSES` (3) transactions out of order in the ledger.

Ordering by `seqProxy` gives accounts with lower sequence numbers a positional advantage, so that's not a solution. We might consider doing an ordering like `CanonicalTxSet`, or maybe just increase `LEDGER_TOTAL_PASSES`.
