### ISSUE TITLE
[XRP EscrowCreate] (Version: [2.1.1])

### ISSUE THREAD

**Issue by xiongjiabing** [XRPLF/rippled#5030]
https://xrpscan.com/tx/995951F3E2112271776E9EA4F6EB2E3D42D7F00020EC7E399C106EBF9B3C7113

hi team,
for this transaction, I find that our deposit logic does not currently support it and can't parse it.

I also searched the following documents:
https://xrpl.org/docs/references/protocol/transactions/types/escrowcreate/

But I find that for this type of transaction, it seems to have an expiration date and returned to the sender when it expires.
so, can we ignore this deposit? even if the user is sent to our deposit address

**Comment by ckeshava** [comment]
Hello,
The specified `EscrowCreate` transaction does not have a `CancelAfter` field. Since it doesn't specify an expiration, I believe the escrow cannot be cancelled.

Have you considered sending a `EscrowFinish` transaction? The `FinishAfter` time has elapsed (25 May, 2024), hence the Escrow amount can be transferred to the destination. Here are the docs: https://xrpl.org/docs/references/protocol/transactions/types/escrowfinish/

Can you elaborate on the issues in parsing the transaction?

**Comment by mvadari** [comment]
Closing this issue as it appears resolved. Please reopen it if there is still an issue.
